#!/usr/bin/env node
/**
 * Adds new firms directly to Supabase.
 * Checks for duplicates by name AND website before inserting.
 * Usage: node scripts/add-firms.mjs
 */
import { config as dotenvConfig } from 'dotenv';
dotenvConfig({ path: '.env.local' });

import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = process.env.NEXT_PUBLIC_SUPABASE_URL;
const KEY = process.env.SUPABASE_SERVICE_ROLE_KEY || process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY;

if (!SUPABASE_URL || !KEY) {
  console.error('Missing Supabase env vars in .env.local');
  process.exit(1);
}

if (!process.env.SUPABASE_SERVICE_ROLE_KEY) {
  console.warn(
    '\n⚠  SUPABASE_SERVICE_ROLE_KEY not set; using anon key. Inserts will likely fail due to RLS.\n'
  );
}

const supabase = createClient(SUPABASE_URL, KEY, {
  auth: { autoRefreshToken: false, persistSession: false },
});

// ── New firms to add ──────────────────────────────────────────────────
const newFirms = [
  // ── San Antonio, TX (6) ───────────────────────────────────────────
  { slug: "cfo-strategic-partners-sa", name: "CFO Strategic Partners - San Antonio", contact: "Team", title: "", email: null, city: "san-antonio", cityLabel: "San Antonio", province: "Texas", country: "United States", services: ["fractional-cfo", "fpa-consulting", "controller-services"], industries: ["healthcare", "professional-services", "technology", "manufacturing"], description: "CFO Strategic Partners provides fractional and interim CFO services in San Antonio, helping businesses with financial strategy, cash flow optimization, and growth planning.", website: "https://cfosp.com", source: "claude_code" },
  { slug: "tax-shield-sa", name: "Tax Shield CPA", contact: "Team", title: "CPA", email: null, city: "san-antonio", cityLabel: "San Antonio", province: "Texas", country: "United States", services: ["tax-advisory", "bookkeeping", "controller-services"], industries: ["professional-services", "retail", "real-estate", "healthcare"], description: "Tax Shield CPA is a San Antonio accounting firm providing tax preparation, bookkeeping, payroll, and business advisory services for individuals and small businesses.", website: "https://taxshieldcpa.com", source: "claude_code" },
  { slug: "padgett-business-sa", name: "Padgett Business Services - San Antonio", contact: "Team", title: "", email: null, city: "san-antonio", cityLabel: "San Antonio", province: "Texas", country: "United States", services: ["bookkeeping", "tax-advisory", "controller-services"], industries: ["professional-services", "retail", "construction", "healthcare"], description: "Padgett Business Services provides small business tax, accounting, and payroll services in San Antonio with personalized support from experienced professionals.", website: "https://www.padgettbusinessservices.com", source: "claude_code" },
  { slug: "badger-cpa-sa", name: "Badger CPA", contact: "Team", title: "CPA", email: null, city: "san-antonio", cityLabel: "San Antonio", province: "Texas", country: "United States", services: ["fractional-cfo", "bookkeeping", "tax-advisory"], industries: ["technology", "professional-services", "healthcare", "retail"], description: "Badger CPA is San Antonio's trusted partner for outsourced accounting, fractional CFOs, and business advisory, located at 18402 US HWY 281 North.", website: "https://badgercpa.com", source: "claude_code" },
  { slug: "adkf-sa", name: "ADKF", contact: "Team", title: "CPA", email: null, city: "san-antonio", cityLabel: "San Antonio", province: "Texas", country: "United States", services: ["tax-advisory", "bookkeeping", "fpa-consulting"], industries: ["professional-services", "construction", "real-estate", "retail"], description: "ADKF is a San Antonio-based accounting firm providing tax planning, business consulting, bookkeeping, and audit services with a commitment to being with clients all the way.", website: "https://www.adkf.com", source: "claude_code" },
  { slug: "now-cfo-san-antonio", name: "NOW CFO - San Antonio", contact: "Team", title: "", email: null, city: "san-antonio", cityLabel: "San Antonio", province: "Texas", country: "United States", services: ["fractional-cfo", "controller-services", "bookkeeping"], industries: ["technology", "manufacturing", "professional-services", "retail"], description: "NOW CFO San Antonio equips business owners with dependable, flexible accounting resources, with consultants trained to solve complex challenges from cash flow management to internal controls.", website: "https://nowcfo.com", source: "claude_code" },

  // ── Fort Worth, TX ────────────────────────────────────────────────
  { slug: "bender-cfo-fort-worth", name: "Bender CFO Services - Fort Worth", contact: "Team", title: "", email: null, city: "fort-worth", cityLabel: "Fort Worth", province: "Texas", country: "United States", services: ["fractional-cfo", "fpa-consulting", "bookkeeping"], industries: ["professional-services", "technology", "retail", "construction"], description: "Bender CFO Services provides fractional CFO services in the Fort Worth area, helping agencies and small businesses with financial strategy, cash flow management, and growth planning.", website: "https://www.bendercfoservices.com", source: "claude_code" },
  { slug: "henry-peters-cpa", name: "Henry & Peters CPAs", contact: "Team", title: "CPA", email: null, city: "fort-worth", cityLabel: "Fort Worth", province: "Texas", country: "United States", services: ["tax-advisory", "fpa-consulting", "controller-services"], industries: ["energy", "construction", "real-estate", "professional-services"], description: "Henry & Peters is a Fort Worth CPA firm established in 1952 providing accounting, auditing, tax planning, and business advisory services to businesses across North Texas.", website: "https://www.henrypeters.com", source: "claude_code" },
  { slug: "now-cfo-fort-worth", name: "NOW CFO - Fort Worth", contact: "Team", title: "", email: null, city: "fort-worth", cityLabel: "Fort Worth", province: "Texas", country: "United States", services: ["fractional-cfo", "controller-services", "bookkeeping"], industries: ["technology", "manufacturing", "professional-services", "retail"], description: "NOW CFO provides ongoing and project-based fractional CFO and controller services in Fort Worth, giving business owners strategic financial visibility and leadership.", website: "https://nowcfo.com", source: "claude_code" },
  { slug: "whitley-penn-fw", name: "Whitley Penn - Fort Worth", contact: "Team", title: "CPA", email: null, city: "fort-worth", cityLabel: "Fort Worth", province: "Texas", country: "United States", services: ["tax-advisory", "fpa-consulting", "controller-services"], industries: ["energy", "real-estate", "manufacturing", "professional-services"], description: "Whitley Penn is a top Texas CPA firm with a Fort Worth office providing assurance, tax, and advisory services to middle-market companies and high-net-worth individuals.", website: "https://www.whitleypenn.com", source: "claude_code" },
  { slug: "frost-pllc", name: "Frost PLLC", contact: "Team", title: "CPA", email: null, city: "fort-worth", cityLabel: "Fort Worth", province: "Texas", country: "United States", services: ["tax-advisory", "bookkeeping", "fpa-consulting"], industries: ["construction", "real-estate", "professional-services", "manufacturing"], description: "Frost PLLC is a Fort Worth CPA firm providing tax, accounting, auditing, and consulting services to businesses and individuals throughout the DFW Metroplex.", website: "https://www.frostpllc.com", source: "claude_code" },

  // ── Las Vegas, NV (5) ──────────────────────────────────────────────
  { slug: "preferred-cfo-lv", name: "Preferred CFO - Las Vegas", contact: "Team", title: "", email: null, city: "las-vegas", cityLabel: "Las Vegas", province: "Nevada", country: "United States", services: ["fractional-cfo", "fpa-consulting", "controller-services"], industries: ["hospitality", "real-estate", "technology", "professional-services"], description: "Preferred CFO provides part-time and fractional CFO services in Las Vegas, offering experienced financial leadership for businesses that need high-level guidance without full-time costs.", website: "https://www.preferredcfo.com", source: "claude_code" },
  { slug: "capital-accountant-lv", name: "Capital Accountant Inc.", contact: "Kelly Bulgatz", title: "CPA, CMA, CFE, CGMA", email: null, city: "las-vegas", cityLabel: "Las Vegas", province: "Nevada", country: "United States", services: ["fractional-cfo", "bookkeeping", "tax-advisory"], industries: ["hospitality", "real-estate", "professional-services", "retail"], description: "Capital Accountant has provided family office, client accounting, and fractional CFO services to high-net-worth individuals, families, and business owners in Las Vegas since 2003.", website: "https://www.cai-cpa.com", source: "claude_code" },
  { slug: "kaizen-cpas-lv", name: "Kaizen CPAs + Advisors", contact: "Team", title: "CPA", email: null, city: "las-vegas", cityLabel: "Las Vegas", province: "Nevada", country: "United States", services: ["fractional-cfo", "tax-advisory", "fpa-consulting"], industries: ["real-estate", "hospitality", "professional-services", "construction"], description: "Kaizen CPAs + Advisors is a Las Vegas CPA firm providing tax planning, business advisory, fractional CFO, and audit services with a focus on real estate and hospitality clients.", website: "https://www.kaizencpas.com", source: "claude_code" },
  { slug: "sdo-cpa-las-vegas", name: "SDO CPA - Las Vegas", contact: "Team", title: "CPA", email: null, city: "las-vegas", cityLabel: "Las Vegas", province: "Nevada", country: "United States", services: ["fractional-cfo", "bookkeeping", "tax-advisory"], industries: ["professional-services", "hospitality", "retail", "technology"], description: "SDO CPA provides cloud-based tax preparation, bookkeeping, payroll, and fractional CFO services to Las Vegas businesses specializing in S-Corps and partnerships.", website: "https://www.sdocpa.com", source: "claude_code" },
  { slug: "now-cfo-las-vegas", name: "NOW CFO - Las Vegas", contact: "Team", title: "", email: null, city: "las-vegas", cityLabel: "Las Vegas", province: "Nevada", country: "United States", services: ["fractional-cfo", "controller-services", "bookkeeping"], industries: ["hospitality", "technology", "professional-services", "retail"], description: "NOW CFO provides fractional CFO, controller, and accounting services in the Las Vegas area, helping businesses develop strategic financial plans.", website: "https://nowcfo.com", source: "claude_code" },

  // ── Sacramento, CA (5) ─────────────────────────────────────────────
  { slug: "lsl-cpas-sacramento", name: "LSL CPAs and Advisors - Sacramento", contact: "Team", title: "CPA", email: null, city: "sacramento", cityLabel: "Sacramento", province: "California", country: "United States", services: ["fractional-cfo", "fpa-consulting", "controller-services"], industries: ["technology", "professional-services", "healthcare", "agriculture"], description: "LSL CPAs and Advisors provides fractional CFO services from their Sacramento office at 500 Capitol Mall, offering outsourced accounting and financial leadership for growing businesses.", website: "https://lslcpas.com", source: "claude_code" },
  { slug: "gilbert-cpa-sacramento", name: "Gilbert Associates CPA", contact: "Team", title: "CPA", email: null, city: "sacramento", cityLabel: "Sacramento", province: "California", country: "United States", services: ["tax-advisory", "bookkeeping", "fpa-consulting"], industries: ["agriculture", "professional-services", "real-estate", "construction"], description: "Gilbert Associates is a Sacramento CPA firm providing tax, audit, accounting, and consulting services to businesses and individuals in the Sacramento Valley.", website: "https://www.gilbertcpa.com", source: "claude_code" },
  { slug: "saag-cpas-sacramento", name: "Sacramento Accounting & Advisory Group", contact: "Team", title: "CPA", email: null, city: "sacramento", cityLabel: "Sacramento", province: "California", country: "United States", services: ["tax-advisory", "fpa-consulting", "controller-services"], industries: ["real-estate", "construction", "healthcare", "professional-services"], description: "Sacramento Accounting & Advisory Group is a full service tax, audit, accounting, and business consulting firm providing comprehensive financial services in Sacramento.", website: "https://www.saagcpas.com", source: "claude_code" },
  { slug: "jill-jacobs-cpa-sacramento", name: "Jill Jacobs & Company Inc.", contact: "Jill Jacobs", title: "CPA", email: null, city: "sacramento", cityLabel: "Sacramento", province: "California", country: "United States", services: ["fractional-cfo", "tax-advisory", "fpa-consulting"], industries: ["technology", "professional-services", "manufacturing", "healthcare"], description: "Jill Jacobs & Company is a trusted Sacramento CPA firm specializing in tax planning, accounting, and CFO services with over 30 years of experience.", website: "https://www.jilljacobscpa.com", source: "claude_code" },
  { slug: "eide-bailly-sacramento", name: "Eide Bailly - Sacramento", contact: "Team", title: "CPA", email: null, city: "sacramento", cityLabel: "Sacramento", province: "California", country: "United States", services: ["tax-advisory", "fpa-consulting", "controller-services"], industries: ["professional-services", "agriculture", "healthcare", "real-estate"], description: "Eide Bailly is a top-25 national CPA firm with a Sacramento office providing audit, tax, consulting, and business advisory services to businesses in Northern California.", website: "https://www.eidebailly.com", source: "claude_code" },

  // ── Oklahoma City, OK (5) ──────────────────────────────────────────
  { slug: "hogan-taylor-okc", name: "HoganTaylor LLP", contact: "Team", title: "CPA", email: null, city: "oklahoma-city", cityLabel: "Oklahoma City", province: "Oklahoma", country: "United States", services: ["fractional-cfo", "tax-advisory", "fpa-consulting"], industries: ["energy", "manufacturing", "healthcare", "professional-services"], description: "HoganTaylor is one of the largest CPA firms in Oklahoma providing assurance, tax, and advisory services from Oklahoma City, with deep expertise in energy, healthcare, and manufacturing.", website: "https://www.hogantaylor.com", source: "claude_code" },
  { slug: "arledge-associates", name: "Arledge & Associates PC", contact: "Team", title: "CPA", email: null, city: "oklahoma-city", cityLabel: "Oklahoma City", province: "Oklahoma", country: "United States", services: ["tax-advisory", "bookkeeping", "controller-services"], industries: ["energy", "professional-services", "construction", "real-estate"], description: "Arledge & Associates, founded in 1983, is an Oklahoma City CPA firm providing tax, accounting, auditing, and business advisory services to tribal governments, businesses, and nonprofits.", website: "https://www.arledge.cpa", source: "claude_code" },
  { slug: "now-cfo-oklahoma-city", name: "NOW CFO - Oklahoma City", contact: "Team", title: "", email: null, city: "oklahoma-city", cityLabel: "Oklahoma City", province: "Oklahoma", country: "United States", services: ["fractional-cfo", "controller-services", "bookkeeping"], industries: ["energy", "technology", "professional-services", "manufacturing"], description: "NOW CFO's Oklahoma City office helps local businesses scale through outsourced, interim accounting support at the CFO, controller, and staff accountant levels.", website: "https://nowcfo.com", source: "claude_code" },
  { slug: "stanfield-odell-okc", name: "Stanfield + O'Dell", contact: "Team", title: "CPA", email: null, city: "oklahoma-city", cityLabel: "Oklahoma City", province: "Oklahoma", country: "United States", services: ["tax-advisory", "fpa-consulting", "bookkeeping"], industries: ["energy", "manufacturing", "professional-services", "construction"], description: "Stanfield + O'Dell is a leading Oklahoma City CPA and advisory firm providing audit, tax, and consulting services to businesses throughout Oklahoma.", website: "https://www.stanfieldodell.com", source: "claude_code" },
  { slug: "core-business-advisors-okc", name: "Core Business Advisors", contact: "Team", title: "", email: null, city: "oklahoma-city", cityLabel: "Oklahoma City", province: "Oklahoma", country: "United States", services: ["fractional-cfo", "fpa-consulting", "controller-services"], industries: ["professional-services", "technology", "energy", "healthcare"], description: "Core Business Advisors provides contract CFO and related accounting and business consulting services to small and mid-size companies in Oklahoma City.", website: "https://okccfo.com", source: "claude_code" },

  // ── Tulsa, OK ──────────────────────────────────────────────────────
  { slug: "hogan-taylor-tulsa", name: "HoganTaylor LLP - Tulsa", contact: "Team", title: "CPA", email: null, city: "tulsa", cityLabel: "Tulsa", province: "Oklahoma", country: "United States", services: ["fractional-cfo", "tax-advisory", "fpa-consulting"], industries: ["energy", "manufacturing", "healthcare", "professional-services"], description: "HoganTaylor's Tulsa office provides comprehensive CPA and advisory services including audit, tax, and strategic financial consulting for businesses across Northeast Oklahoma.", website: "https://www.hogantaylor.com", source: "claude_code" },
  { slug: "cynthia-pogue-baker-tulsa", name: "Cynthia Pogue Baker CPA", contact: "Cynthia Pogue Baker", title: "CPA", email: null, city: "tulsa", cityLabel: "Tulsa", province: "Oklahoma", country: "United States", services: ["tax-advisory", "bookkeeping", "fpa-consulting"], industries: ["professional-services", "energy", "real-estate", "retail"], description: "Cynthia Pogue Baker CPA is a full-service Tulsa accounting firm providing tax preparation, bookkeeping, payroll, and business consulting services.", website: "https://www.tulsacpa.com", source: "claude_code" },
  { slug: "cbew-tulsa", name: "CBEW Professional Group", contact: "Team", title: "CPA", email: null, city: "tulsa", cityLabel: "Tulsa", province: "Oklahoma", country: "United States", services: ["tax-advisory", "bookkeeping", "controller-services"], industries: ["energy", "construction", "professional-services", "real-estate"], description: "CBEW Professional Group is a Tulsa CPA firm providing tax planning, audit, bookkeeping, and business consulting services to businesses and individuals in Oklahoma.", website: "https://www.cbew.com", source: "claude_code" },
  { slug: "forvis-mazars-tulsa", name: "Forvis Mazars - Tulsa", contact: "Team", title: "CPA", email: null, city: "tulsa", cityLabel: "Tulsa", province: "Oklahoma", country: "United States", services: ["tax-advisory", "fpa-consulting", "controller-services"], industries: ["energy", "manufacturing", "professional-services", "healthcare"], description: "Forvis Mazars is a top-10 national accounting firm with a Tulsa office providing assurance, tax, and advisory services to businesses across Northeast Oklahoma.", website: "https://www.forvismazars.us", source: "claude_code" },
  { slug: "hnb-cpa-tulsa", name: "HNB CPAs", contact: "Team", title: "CPA", email: null, city: "tulsa", cityLabel: "Tulsa", province: "Oklahoma", country: "United States", services: ["tax-advisory", "fpa-consulting", "controller-services"], industries: ["energy", "manufacturing", "professional-services", "healthcare"], description: "HNB CPAs provides business advisory, tax, and accounting services in Tulsa with dedicated industry focus on oil and gas, manufacturing, and healthcare sectors.", website: "https://www.hnbcpa.com", source: "claude_code" },

  // ── Birmingham, AL ────────────────────────────────────────────────
  { slug: "warren-averett-bhm", name: "Warren Averett", contact: "Team", title: "CPA", email: null, city: "birmingham", cityLabel: "Birmingham", province: "Alabama", country: "United States", services: ["fractional-cfo", "tax-advisory", "fpa-consulting"], industries: ["healthcare", "manufacturing", "professional-services", "construction"], description: "Warren Averett is one of the largest accounting and advisory firms in the Southeast with a Birmingham office, providing CFO advisory, tax, audit, and consulting services.", website: "https://www.warrenaverett.com", source: "claude_code" },
  { slug: "jackson-thornton-bhm", name: "Jackson Thornton", contact: "Team", title: "CPA", email: null, city: "birmingham", cityLabel: "Birmingham", province: "Alabama", country: "United States", services: ["tax-advisory", "fpa-consulting", "controller-services"], industries: ["manufacturing", "healthcare", "construction", "professional-services"], description: "Jackson Thornton is an Alabama-based CPA and advisory firm with a Birmingham presence, providing audit, tax, and business consulting services since 1915.", website: "https://www.jacksonthornton.com", source: "claude_code" },
  { slug: "bmss-advisors", name: "BMSS Advisors", contact: "Team", title: "CPA", email: null, city: "birmingham", cityLabel: "Birmingham", province: "Alabama", country: "United States", services: ["fractional-cfo", "tax-advisory", "fpa-consulting"], industries: ["healthcare", "construction", "manufacturing", "professional-services"], description: "BMSS Advisors is a leading Birmingham CPA firm offering audit, tax, consulting, and CFO advisory services, recognized as one of the top 200 accounting firms in the US.", website: "https://www.bmss.com", source: "claude_code" },
  { slug: "carr-riggs-ingram-bhm", name: "Carr, Riggs & Ingram - Birmingham", contact: "Team", title: "CPA", email: null, city: "birmingham", cityLabel: "Birmingham", province: "Alabama", country: "United States", services: ["tax-advisory", "fpa-consulting", "controller-services"], industries: ["healthcare", "manufacturing", "professional-services", "real-estate"], description: "Carr, Riggs & Ingram is a top-25 national accounting firm with a Birmingham office providing audit, tax, advisory, and technology consulting services.", website: "https://www.cricpa.com", source: "claude_code" },
  { slug: "aldridge-borden-bhm", name: "Aldridge, Borden & Company", contact: "Team", title: "CPA", email: null, city: "birmingham", cityLabel: "Birmingham", province: "Alabama", country: "United States", services: ["tax-advisory", "bookkeeping", "fpa-consulting"], industries: ["professional-services", "real-estate", "construction", "healthcare"], description: "Aldridge, Borden & Company is a Birmingham CPA firm providing tax planning, accounting, auditing, and business advisory services to businesses and individuals throughout Alabama.", website: "https://www.aldridgeborden.com", source: "claude_code" },

  // ── Louisville, KY ────────────────────────────────────────────────
  { slug: "blue-co-louisville", name: "Blue & Co. - Louisville", contact: "Team", title: "CPA", email: null, city: "louisville", cityLabel: "Louisville", province: "Kentucky", country: "United States", services: ["fractional-cfo", "tax-advisory", "fpa-consulting"], industries: ["healthcare", "manufacturing", "professional-services", "construction"], description: "Blue & Co. is a leading regional CPA firm with a Louisville office providing audit, tax, and advisory services with deep expertise in healthcare and manufacturing.", website: "https://www.blueandco.com", source: "claude_code" },
  { slug: "mountjoy-chilton-medley", name: "MCM CPAs & Advisors", contact: "Team", title: "CPA", email: null, city: "louisville", cityLabel: "Louisville", province: "Kentucky", country: "United States", services: ["tax-advisory", "fpa-consulting", "controller-services"], industries: ["manufacturing", "healthcare", "professional-services", "construction"], description: "MCM CPAs & Advisors is a Louisville-based full-service accounting firm providing audit, tax, and business advisory services to companies throughout Kentucky and Indiana.", website: "https://www.mcmcpa.com", source: "claude_code" },
  { slug: "dean-dorton-louisville", name: "Dean Dorton", contact: "Team", title: "CPA", email: null, city: "louisville", cityLabel: "Louisville", province: "Kentucky", country: "United States", services: ["fractional-cfo", "tax-advisory", "fpa-consulting"], industries: ["technology", "healthcare", "manufacturing", "professional-services"], description: "Dean Dorton is one of Kentucky's largest CPA and advisory firms providing assurance, tax, technology, and outsourced CFO services from their Louisville office.", website: "https://www.deandorton.com", source: "claude_code" },
  { slug: "jones-nale-mattingly", name: "Jones, Nale & Mattingly PLC", contact: "Team", title: "CPA", email: null, city: "louisville", cityLabel: "Louisville", province: "Kentucky", country: "United States", services: ["tax-advisory", "bookkeeping", "controller-services"], industries: ["professional-services", "manufacturing", "retail", "real-estate"], description: "Jones, Nale & Mattingly is a Louisville CPA firm founded in 1935 providing tax, audit, accounting, and business consulting services to businesses across Kentucky.", website: "https://www.jnmcpa.com", source: "claude_code" },
  { slug: "strothman-co-louisville", name: "Strothman and Company", contact: "Team", title: "CPA", email: null, city: "louisville", cityLabel: "Louisville", province: "Kentucky", country: "United States", services: ["tax-advisory", "fpa-consulting", "controller-services"], industries: ["manufacturing", "construction", "professional-services", "healthcare"], description: "Strothman and Company is a Louisville CPA firm providing accounting, tax, audit, and advisory services with a focus on privately held businesses and their owners.", website: "https://www.strothman.com", source: "claude_code" },

  // ── New Orleans, LA ───────────────────────────────────────────────
  { slug: "postlethwaite-netterville", name: "Postlethwaite & Netterville (P&N)", contact: "Team", title: "CPA", email: null, city: "new-orleans", cityLabel: "New Orleans", province: "Louisiana", country: "United States", services: ["fractional-cfo", "tax-advisory", "fpa-consulting"], industries: ["energy", "healthcare", "professional-services", "construction"], description: "Postlethwaite & Netterville is the largest Louisiana-based CPA firm with a New Orleans office, providing audit, tax, and advisory services with deep expertise in energy and healthcare.", website: "https://www.pncpa.com", source: "claude_code" },
  { slug: "laporte-cpa-nola", name: "LaPorte CPAs & Business Advisors", contact: "Team", title: "CPA", email: null, city: "new-orleans", cityLabel: "New Orleans", province: "Louisiana", country: "United States", services: ["fractional-cfo", "tax-advisory", "fpa-consulting"], industries: ["energy", "construction", "healthcare", "professional-services"], description: "LaPorte is a leading Gulf South CPA firm with a New Orleans office providing audit, tax, consulting, and outsourced CFO services to businesses throughout Louisiana.", website: "https://www.laporte.com", source: "claude_code" },
  { slug: "bourgeois-bennett-nola", name: "Bourgeois Bennett", contact: "Team", title: "CPA", email: null, city: "new-orleans", cityLabel: "New Orleans", province: "Louisiana", country: "United States", services: ["tax-advisory", "fpa-consulting", "controller-services"], industries: ["real-estate", "hospitality", "energy", "professional-services"], description: "Bourgeois Bennett is one of the largest locally-owned regional accounting firms in Louisiana, celebrating its centennial and providing tax, accounting, and financial reporting services.", website: "https://www.bb-cpa.com", source: "claude_code" },
  { slug: "ericksen-krentel-nola", name: "Ericksen Krentel CPAs", contact: "Team", title: "CPA", email: null, city: "new-orleans", cityLabel: "New Orleans", province: "Louisiana", country: "United States", services: ["tax-advisory", "bookkeeping", "controller-services"], industries: ["hospitality", "healthcare", "construction", "professional-services"], description: "Ericksen Krentel has provided unparalleled quality service to the South Louisiana and Gulf Coast region since 1960, serving governmental entities, nonprofits, hospitality, and construction clients.", website: "https://www.ericksenkrentel.com", source: "claude_code" },
  { slug: "duplantier-hrapmann-nola", name: "Duplantier, Hrapmann, Hogan & Maher LLP", contact: "Team", title: "CPA", email: null, city: "new-orleans", cityLabel: "New Orleans", province: "Louisiana", country: "United States", services: ["tax-advisory", "fpa-consulting", "controller-services"], industries: ["professional-services", "hospitality", "real-estate", "healthcare"], description: "Duplantier, Hrapmann, Hogan & Maher is a certified public accounting partnership in Metairie serving the New Orleans area with offices in Slidell, Houma, and Covington.", website: "https://www.dhhmcpa.com", source: "claude_code" },

  // ── Greenville, SC ────────────────────────────────────────────────
  { slug: "cherry-bekaert-greenville", name: "Cherry Bekaert - Greenville", contact: "Team", title: "CPA", email: null, city: "greenville-sc", cityLabel: "Greenville", province: "South Carolina", country: "United States", services: ["fractional-cfo", "tax-advisory", "fpa-consulting"], industries: ["manufacturing", "technology", "healthcare", "professional-services"], description: "Cherry Bekaert is a nationally recognized CPA firm with a Greenville office providing assurance, tax, advisory, and outsourced CFO services to businesses in the Upstate.", website: "https://www.cbh.com", source: "claude_code" },
  { slug: "elliott-davis-greenville", name: "Elliott Davis - Greenville", contact: "Team", title: "CPA", email: null, city: "greenville-sc", cityLabel: "Greenville", province: "South Carolina", country: "United States", services: ["tax-advisory", "fpa-consulting", "controller-services"], industries: ["manufacturing", "technology", "healthcare", "professional-services"], description: "Elliott Davis is a top-40 accounting and consulting firm headquartered in Greenville, SC providing tax, audit, and advisory services to middle-market companies.", website: "https://www.elliottdavis.com", source: "claude_code" },
  { slug: "manley-garvin-greenville", name: "Manley Garvin LLC", contact: "Team", title: "CPA", email: null, city: "greenville-sc", cityLabel: "Greenville", province: "South Carolina", country: "United States", services: ["tax-advisory", "bookkeeping", "fpa-consulting"], industries: ["manufacturing", "professional-services", "retail", "construction"], description: "Manley Garvin is a Greenville, SC accounting firm offering tax planning, audit, bookkeeping, and business advisory services for individuals and businesses.", website: "https://www.manleygarvin.com", source: "claude_code" },
  { slug: "cfo-focus-greenville", name: "CFO Focus", contact: "Team", title: "", email: null, city: "greenville-sc", cityLabel: "Greenville", province: "South Carolina", country: "United States", services: ["fractional-cfo", "fpa-consulting", "controller-services"], industries: ["manufacturing", "technology", "professional-services", "healthcare"], description: "CFO Focus provides fractional CFO and financial consulting services in the Greenville-Spartanburg area, offering strategic financial leadership to growing businesses.", website: "https://cfofocus.com", source: "claude_code" },
  { slug: "smith-howard-greenville", name: "Smith Howard CPA", contact: "Team", title: "CPA", email: null, city: "greenville-sc", cityLabel: "Greenville", province: "South Carolina", country: "United States", services: ["tax-advisory", "bookkeeping", "controller-services"], industries: ["manufacturing", "construction", "professional-services", "retail"], description: "Smith Howard provides tax, accounting, audit, and advisory services in the Greenville area, focusing on small and mid-sized businesses and their owners.", website: "https://www.smith-howard.com", source: "claude_code" },

  // ── Columbia, SC ───────────────────────────────────────────────────
  { slug: "dixon-hughes-columbia", name: "Dixon Hughes Goodman - Columbia", contact: "Team", title: "CPA", email: null, city: "columbia-sc", cityLabel: "Columbia", province: "South Carolina", country: "United States", services: ["fractional-cfo", "tax-advisory", "fpa-consulting"], industries: ["healthcare", "manufacturing", "technology", "professional-services"], description: "Dixon Hughes Goodman (now Forvis Mazars) has a Columbia office providing assurance, tax, and advisory services to businesses across the Midlands of South Carolina.", website: "https://www.forvismazars.us", source: "claude_code" },
  { slug: "webster-rogers-columbia", name: "Webster Rogers LLP", contact: "Team", title: "CPA", email: null, city: "columbia-sc", cityLabel: "Columbia", province: "South Carolina", country: "United States", services: ["tax-advisory", "fpa-consulting", "controller-services"], industries: ["professional-services", "real-estate", "construction", "healthcare"], description: "Webster Rogers is a South Carolina CPA firm with a Columbia office providing audit, tax, and advisory services to businesses and organizations throughout the state.", website: "https://www.websterrogers.com", source: "claude_code" },
  { slug: "mcnair-mclemore-columbia", name: "McNair, McLemore, Middlebrooks & Co.", contact: "Team", title: "CPA", email: null, city: "columbia-sc", cityLabel: "Columbia", province: "South Carolina", country: "United States", services: ["tax-advisory", "bookkeeping", "fpa-consulting"], industries: ["professional-services", "real-estate", "healthcare", "construction"], description: "McNair McLemore is a Columbia, SC CPA firm providing accounting, auditing, tax, and business consulting services to public and private organizations.", website: "https://www.mcnaircpa.com", source: "claude_code" },
  { slug: "mauldin-jenkins-columbia", name: "Mauldin & Jenkins - Columbia", contact: "Team", title: "CPA", email: null, city: "columbia-sc", cityLabel: "Columbia", province: "South Carolina", country: "United States", services: ["tax-advisory", "controller-services", "fpa-consulting"], industries: ["professional-services", "healthcare", "manufacturing", "construction"], description: "Mauldin & Jenkins is a top-100 accounting firm with a Columbia office providing assurance, tax, advisory, and consulting services to businesses across South Carolina.", website: "https://www.mjcpa.com", source: "claude_code" },
  { slug: "cfo-suite-columbia", name: "CFO Suite - Columbia", contact: "Team", title: "", email: null, city: "columbia-sc", cityLabel: "Columbia", province: "South Carolina", country: "United States", services: ["fractional-cfo", "controller-services", "fpa-consulting"], industries: ["professional-services", "technology", "healthcare", "manufacturing"], description: "CFO Suite provides fractional and interim CFO services in the Columbia area, connecting businesses with experienced financial leaders for strategic guidance.", website: "https://www.cfosuite.com", source: "claude_code" },

  // ── Hartford, CT ──────────────────────────────────────────────────
  { slug: "cohn-reznick-hartford", name: "CohnReznick - Hartford", contact: "Team", title: "CPA", email: null, city: "hartford", cityLabel: "Hartford", province: "Connecticut", country: "United States", services: ["fractional-cfo", "tax-advisory", "fpa-consulting"], industries: ["manufacturing", "technology", "healthcare", "professional-services"], description: "CohnReznick is a top-10 national accounting firm with a Hartford office providing audit, tax, advisory, and outsourced CFO services to businesses in Connecticut.", website: "https://www.cohnreznick.com", source: "claude_code" },
  { slug: "whittlesey-hartford", name: "Whittlesey", contact: "Team", title: "CPA", email: null, city: "hartford", cityLabel: "Hartford", province: "Connecticut", country: "United States", services: ["tax-advisory", "fpa-consulting", "controller-services"], industries: ["manufacturing", "professional-services", "healthcare", "technology"], description: "Whittlesey is Connecticut's largest CPA and consulting firm, ranked among the top 10 in New England, recognized as a Best of the Best Firm and Top 200 Accounting Firm.", website: "https://www.wadvising.com", source: "claude_code" },
  { slug: "mahoney-sabol-hartford", name: "Mahoney Sabol", contact: "Team", title: "CPA", email: null, city: "hartford", cityLabel: "Hartford", province: "Connecticut", country: "United States", services: ["tax-advisory", "bookkeeping", "fpa-consulting"], industries: ["construction", "manufacturing", "professional-services", "real-estate"], description: "Mahoney Sabol is a Hartford-area CPA firm providing audit, tax, and advisory services with recognized expertise in construction, manufacturing, and real estate industries.", website: "https://www.mahoneysabol.com", source: "claude_code" },
  { slug: "fiondella-milone-hartford", name: "Fiondella, Milone & LaSaracina LLP", contact: "Team", title: "CPA", email: null, city: "hartford", cityLabel: "Hartford", province: "Connecticut", country: "United States", services: ["tax-advisory", "controller-services", "fpa-consulting"], industries: ["professional-services", "manufacturing", "healthcare", "construction"], description: "Fiondella, Milone & LaSaracina is a Glastonbury-Hartford area CPA firm providing audit, tax, and business consulting services to closely held businesses and their owners.", website: "https://www.fmlcpas.com", source: "claude_code" },
  { slug: "marcum-hartford", name: "Marcum LLP - Hartford", contact: "Team", title: "CPA", email: null, city: "hartford", cityLabel: "Hartford", province: "Connecticut", country: "United States", services: ["fractional-cfo", "tax-advisory", "fpa-consulting"], industries: ["manufacturing", "technology", "healthcare", "professional-services"], description: "Marcum LLP is a top-15 national accounting firm with a Hartford-area office providing assurance, tax, advisory, and outsourced CFO services to Connecticut businesses.", website: "https://www.marcumllp.com", source: "claude_code" },

  // ── Buffalo, NY ───────────────────────────────────────────────────
  { slug: "freed-maxick-buffalo", name: "Freed Maxick CPAs", contact: "Team", title: "CPA", email: null, city: "buffalo", cityLabel: "Buffalo", province: "New York", country: "United States", services: ["fractional-cfo", "tax-advisory", "fpa-consulting"], industries: ["manufacturing", "technology", "healthcare", "professional-services"], description: "Freed Maxick is one of Western New York's largest CPA firms providing accounting, tax, audit, and consulting services from their Buffalo headquarters.", website: "https://www.freedmaxick.com", source: "claude_code" },
  { slug: "lumsden-mccormick-buffalo", name: "Lumsden McCormick", contact: "Team", title: "CPA", email: null, city: "buffalo", cityLabel: "Buffalo", province: "New York", country: "United States", services: ["tax-advisory", "fpa-consulting", "controller-services"], industries: ["manufacturing", "professional-services", "healthcare", "construction"], description: "Lumsden McCormick is a Buffalo-based CPA and business advisory firm providing audit, tax, and consulting services to organizations throughout Western New York.", website: "https://www.lumsdencpa.com", source: "claude_code" },
  { slug: "chiampou-travis-buffalo", name: "Chiampou Travis Besaw & Kershner LLP", contact: "Team", title: "CPA", email: null, city: "buffalo", cityLabel: "Buffalo", province: "New York", country: "United States", services: ["tax-advisory", "bookkeeping", "fpa-consulting"], industries: ["professional-services", "manufacturing", "retail", "construction"], description: "Chiampou Travis Besaw & Kershner is a Buffalo CPA firm offering accounting, tax, audit, and financial advisory services for businesses and individuals in WNY.", website: "https://www.ctbk.com", source: "claude_code" },
  { slug: "dopkins-company-buffalo", name: "Dopkins & Company", contact: "Team", title: "CPA", email: null, city: "buffalo", cityLabel: "Buffalo", province: "New York", country: "United States", services: ["tax-advisory", "fpa-consulting", "controller-services"], industries: ["manufacturing", "healthcare", "professional-services", "real-estate"], description: "Dopkins & Company is the largest locally owned CPA firm in Western New York providing accounting, auditing, tax, and advisory services from their Buffalo office.", website: "https://www.dopkins.com", source: "claude_code" },
  { slug: "brock-schechter-buffalo", name: "Brock Schechter & Polakoff LLP", contact: "Team", title: "CPA", email: null, city: "buffalo", cityLabel: "Buffalo", province: "New York", country: "United States", services: ["tax-advisory", "bookkeeping", "controller-services"], industries: ["professional-services", "manufacturing", "healthcare", "retail"], description: "Brock Schechter & Polakoff is a Buffalo-area accounting firm providing audit, tax, and business advisory services to companies and individuals throughout Western New York.", website: "https://www.bspcpa.com", source: "claude_code" },

  // ── Providence, RI ────────────────────────────────────────────────
  { slug: "kahn-litwin-renza", name: "KLR (Kahn Litwin Renza)", contact: "Team", title: "CPA", email: null, city: "providence", cityLabel: "Providence", province: "Rhode Island", country: "United States", services: ["fractional-cfo", "tax-advisory", "fpa-consulting"], industries: ["manufacturing", "technology", "healthcare", "professional-services"], description: "KLR is the largest CPA firm headquartered in New England, providing audit, tax, and advisory services from their Providence office with expertise across diverse industries.", website: "https://www.kahnlitwin.com", source: "claude_code" },
  { slug: "sansiveri-cpa-pvd", name: "Sansiveri CPA", contact: "Team", title: "CPA", email: null, city: "providence", cityLabel: "Providence", province: "Rhode Island", country: "United States", services: ["tax-advisory", "fpa-consulting", "controller-services"], industries: ["professional-services", "manufacturing", "healthcare", "real-estate"], description: "Sansiveri CPA is an award-winning Providence firm providing tailored assurance, tax, client accounting services, and advisory solutions, named 2025 Best Accounting Firm to Work For.", website: "https://www.sansiveri.com", source: "claude_code" },
  { slug: "marcum-providence", name: "Marcum LLP - Providence", contact: "Team", title: "CPA", email: null, city: "providence", cityLabel: "Providence", province: "Rhode Island", country: "United States", services: ["fractional-cfo", "tax-advisory", "fpa-consulting"], industries: ["technology", "manufacturing", "healthcare", "professional-services"], description: "Marcum LLP is a top-15 national accounting firm with a Providence office providing assurance, tax, advisory, and outsourced CFO services to businesses in Rhode Island.", website: "https://www.marcumllp.com", source: "claude_code" },
  { slug: "damico-forrest-pvd", name: "D'Amico Forrest CPA", contact: "Team", title: "CPA", email: null, city: "providence", cityLabel: "Providence", province: "Rhode Island", country: "United States", services: ["tax-advisory", "bookkeeping", "controller-services"], industries: ["professional-services", "retail", "real-estate", "healthcare"], description: "D'Amico Forrest CPA is a Providence and Cranston-area accounting firm providing tax preparation, bookkeeping, and financial advisory services to individuals and small businesses.", website: "https://www.damicoforrestcpa.com", source: "claude_code" },
  { slug: "disanto-priest-pvd", name: "DiSanto, Priest & Co.", contact: "Team", title: "CPA", email: null, city: "providence", cityLabel: "Providence", province: "Rhode Island", country: "United States", services: ["tax-advisory", "fpa-consulting", "controller-services"], industries: ["professional-services", "construction", "manufacturing", "healthcare"], description: "DiSanto, Priest & Co. is one of Rhode Island's top CPA firms, making Accounting Today's Top 100 Firms list for the ninth consecutive year, providing financial advisory and tax services.", website: "https://www.disantopriest.com", source: "claude_code" },

  // ── Cincinnati, OH ────────────────────────────────────────────────
  { slug: "barnes-dennig-cinci", name: "Barnes Dennig", contact: "Team", title: "CPA", email: null, city: "cincinnati", cityLabel: "Cincinnati", province: "Ohio", country: "United States", services: ["fractional-cfo", "tax-advisory", "fpa-consulting"], industries: ["manufacturing", "technology", "healthcare", "professional-services"], description: "Barnes Dennig is a Cincinnati-based CPA and business advisory firm providing audit, tax, and outsourced CFO services to businesses in the Greater Cincinnati tri-state area.", website: "https://www.barnesdennig.com", source: "claude_code" },
  { slug: "clark-schaefer-hackett", name: "Clark Schaefer Hackett (CSH)", contact: "Team", title: "CPA", email: null, city: "cincinnati", cityLabel: "Cincinnati", province: "Ohio", country: "United States", services: ["tax-advisory", "fpa-consulting", "controller-services"], industries: ["manufacturing", "healthcare", "professional-services", "construction"], description: "Clark Schaefer Hackett is one of the largest Ohio-based CPA firms with a Cincinnati office providing audit, tax, and strategic advisory services to mid-market businesses.", website: "https://www.cshco.com", source: "claude_code" },
  { slug: "kirsch-cpa-cincinnati", name: "Kirsch CPA Firm", contact: "Team", title: "CPA", email: null, city: "cincinnati", cityLabel: "Cincinnati", province: "Ohio", country: "United States", services: ["fractional-cfo", "tax-advisory", "bookkeeping"], industries: ["professional-services", "manufacturing", "technology", "retail"], description: "Kirsch CPA Firm provides tax preparation, outsourced accounting, fractional CFO, and business advisory services to Cincinnati-area businesses.", website: "https://kirschcpa.com", source: "claude_code" },
  { slug: "brixey-meyer-cincinnati", name: "Brixey & Meyer", contact: "Team", title: "CPA", email: null, city: "cincinnati", cityLabel: "Cincinnati", province: "Ohio", country: "United States", services: ["fractional-cfo", "controller-services", "fpa-consulting"], industries: ["technology", "manufacturing", "professional-services", "healthcare"], description: "Brixey & Meyer provides CFO, controller, and accounting support services from their Cincinnati office at 1111 St. Gregory St, helping businesses with financial leadership.", website: "https://www.brixeyandmeyer.com", source: "claude_code" },
  { slug: "plante-moran-cinci", name: "Plante Moran - Cincinnati", contact: "Team", title: "CPA", email: null, city: "cincinnati", cityLabel: "Cincinnati", province: "Ohio", country: "United States", services: ["fractional-cfo", "tax-advisory", "fpa-consulting"], industries: ["manufacturing", "technology", "healthcare", "professional-services"], description: "Plante Moran is a top-15 national accounting firm with a Cincinnati office providing assurance, tax, consulting, and wealth management services.", website: "https://www.plantemoran.com", source: "claude_code" },

  // ── Omaha, NE ──────────────────────────────────────────────────────
  { slug: "lutz-omaha", name: "Lutz", contact: "Team", title: "CPA", email: null, city: "omaha", cityLabel: "Omaha", province: "Nebraska", country: "United States", services: ["fractional-cfo", "tax-advisory", "fpa-consulting"], industries: ["manufacturing", "technology", "professional-services", "construction"], description: "Lutz is one of Nebraska's largest CPA firms headquartered in Omaha, providing accounting, tax, consulting, talent, and financial services to businesses across the Midwest.", website: "https://www.lutz.us", source: "claude_code" },
  { slug: "mcgladrey-omaha", name: "RSM US - Omaha", contact: "Team", title: "CPA", email: null, city: "omaha", cityLabel: "Omaha", province: "Nebraska", country: "United States", services: ["fractional-cfo", "tax-advisory", "fpa-consulting"], industries: ["manufacturing", "technology", "healthcare", "professional-services"], description: "RSM US is a leading national accounting firm with an Omaha office providing audit, tax, and consulting services with deep expertise in middle-market businesses.", website: "https://rsmus.com", source: "claude_code" },
  { slug: "hayes-associates-omaha", name: "Hayes & Associates", contact: "Team", title: "CPA", email: null, city: "omaha", cityLabel: "Omaha", province: "Nebraska", country: "United States", services: ["tax-advisory", "fpa-consulting", "controller-services"], industries: ["professional-services", "manufacturing", "healthcare", "real-estate"], description: "Hayes & Associates is an Omaha CPA firm providing audit, tax, and consulting services to businesses and organizations throughout Nebraska and Iowa.", website: "https://www.hayescpa.com", source: "claude_code" },
  { slug: "seim-johnson-omaha", name: "Seim Johnson", contact: "Team", title: "CPA", email: null, city: "omaha", cityLabel: "Omaha", province: "Nebraska", country: "United States", services: ["tax-advisory", "bookkeeping", "controller-services"], industries: ["professional-services", "agriculture", "construction", "manufacturing"], description: "Seim Johnson is an Omaha-based CPA firm offering accounting, audit, tax, and business consulting services to businesses, nonprofits, and individuals across Nebraska.", website: "https://www.seimjohnson.com", source: "claude_code" },
  { slug: "frankel-zacharia-omaha", name: "Frankel Zacharia", contact: "Team", title: "CPA", email: null, city: "omaha", cityLabel: "Omaha", province: "Nebraska", country: "United States", services: ["tax-advisory", "fpa-consulting", "bookkeeping"], industries: ["professional-services", "real-estate", "retail", "manufacturing"], description: "Frankel Zacharia is an Omaha CPA firm providing tax, accounting, and advisory services with a focus on privately held companies and their owners.", website: "https://www.fzacpa.com", source: "claude_code" },

  // ── Boise, ID ──────────────────────────────────────────────────────
  { slug: "eide-bailly-boise", name: "Eide Bailly - Boise", contact: "Team", title: "CPA", email: null, city: "boise", cityLabel: "Boise", province: "Idaho", country: "United States", services: ["fractional-cfo", "tax-advisory", "fpa-consulting"], industries: ["technology", "agriculture", "manufacturing", "professional-services"], description: "Eide Bailly is a top-25 national CPA firm with a Boise office providing audit, tax, and advisory services with strong expertise in technology, agriculture, and manufacturing.", website: "https://www.eidebailly.com", source: "claude_code" },
  { slug: "cooper-norman-boise", name: "Cooper Norman", contact: "Team", title: "CPA", email: null, city: "boise", cityLabel: "Boise", province: "Idaho", country: "United States", services: ["tax-advisory", "fpa-consulting", "controller-services"], industries: ["agriculture", "professional-services", "construction", "real-estate"], description: "Cooper Norman is a leading Idaho CPA firm with a Boise office providing audit, tax, and advisory services to businesses and individuals throughout Idaho.", website: "https://www.coopernorman.com", source: "claude_code" },
  { slug: "harris-cpa-boise", name: "Harris CPAs", contact: "Team", title: "CPA", email: null, city: "boise", cityLabel: "Boise", province: "Idaho", country: "United States", services: ["tax-advisory", "bookkeeping", "fpa-consulting"], industries: ["professional-services", "technology", "construction", "retail"], description: "Harris CPAs provides personalized tax, accounting, and business advisory services to businesses and individuals in the Boise area.", website: "https://www.harriscpas.com", source: "claude_code" },
  { slug: "presnell-gage-boise", name: "Presnell Gage", contact: "Team", title: "CPA", email: null, city: "boise", cityLabel: "Boise", province: "Idaho", country: "United States", services: ["tax-advisory", "fpa-consulting", "controller-services"], industries: ["agriculture", "technology", "professional-services", "manufacturing"], description: "Presnell Gage is an Idaho CPA firm providing accounting, tax, and business advisory services with offices serving the Treasure Valley and surrounding communities.", website: "https://www.presnellgage.com", source: "claude_code" },
  { slug: "now-cfo-boise", name: "NOW CFO - Boise", contact: "Team", title: "", email: null, city: "boise", cityLabel: "Boise", province: "Idaho", country: "United States", services: ["fractional-cfo", "controller-services", "bookkeeping"], industries: ["technology", "manufacturing", "professional-services", "construction"], description: "NOW CFO provides fractional CFO, controller, and staff accountant services in the Boise metro area, helping businesses develop strategic financial plans.", website: "https://nowcfo.com", source: "claude_code" },

  // ── Albuquerque, NM ───────────────────────────────────────────────
  { slug: "all-business-cpa-abq", name: "All Business CPA", contact: "Team", title: "CPA", email: null, city: "albuquerque", cityLabel: "Albuquerque", province: "New Mexico", country: "United States", services: ["fractional-cfo", "tax-advisory", "bookkeeping"], industries: ["energy", "healthcare", "professional-services", "construction"], description: "All Business CPA provides accounting, tax planning, bookkeeping, and financial advisory services to businesses and individuals in Albuquerque and across New Mexico.", website: "https://www.allbusinesscpa.com", source: "claude_code" },
  { slug: "pulakos-alongi-abq", name: "Pulakos & Alongi", contact: "Team", title: "CPA", email: null, city: "albuquerque", cityLabel: "Albuquerque", province: "New Mexico", country: "United States", services: ["tax-advisory", "fpa-consulting", "controller-services"], industries: ["professional-services", "healthcare", "construction", "real-estate"], description: "Pulakos & Alongi is an Albuquerque CPA firm offering tax, audit, and business consulting services to businesses and individuals throughout New Mexico.", website: "https://www.pulakos.com", source: "claude_code" },
  { slug: "hinkle-landers-abq", name: "Hinkle + Landers PC", contact: "Team", title: "CPA", email: null, city: "albuquerque", cityLabel: "Albuquerque", province: "New Mexico", country: "United States", services: ["tax-advisory", "bookkeeping", "controller-services"], industries: ["professional-services", "energy", "construction", "retail"], description: "Hinkle + Landers is an Albuquerque CPA firm providing tax planning, audit, accounting, and business advisory services to individuals and businesses across New Mexico.", website: "https://www.hinklecpa.com", source: "claude_code" },
  { slug: "jon-bell-cpa-abq", name: "Jon Bell CPA & Associates", contact: "Jon Bell", title: "CPA", email: null, city: "albuquerque", cityLabel: "Albuquerque", province: "New Mexico", country: "United States", services: ["tax-advisory", "bookkeeping", "fpa-consulting"], industries: ["professional-services", "healthcare", "real-estate", "retail"], description: "Jon Bell CPA & Associates is an experienced Albuquerque CPA firm providing tax planning, accounting, bookkeeping, and financial advisory services to businesses and individuals.", website: "https://www.jonbellcpa.com", source: "claude_code" },
  { slug: "wall-ross-abq", name: "Wall, Smith, Bateman", contact: "Team", title: "CPA", email: null, city: "albuquerque", cityLabel: "Albuquerque", province: "New Mexico", country: "United States", services: ["tax-advisory", "fpa-consulting", "controller-services"], industries: ["professional-services", "energy", "healthcare", "construction"], description: "Wall, Smith, Bateman is an Albuquerque-based CPA firm providing comprehensive audit, tax, and advisory services to businesses and organizations in New Mexico.", website: "https://www.wsbcpa.com", source: "claude_code" },

  // ── Tucson, AZ ─────────────────────────────────────────────────────
  { slug: "beach-fleischman-tucson", name: "BeachFleischman PLLC", contact: "Team", title: "CPA", email: null, city: "tucson", cityLabel: "Tucson", province: "Arizona", country: "United States", services: ["fractional-cfo", "tax-advisory", "fpa-consulting"], industries: ["healthcare", "technology", "manufacturing", "professional-services"], description: "BeachFleischman is the largest locally owned CPA firm in Southern Arizona, providing audit, tax, consulting, and CFO advisory services from their Tucson and Phoenix offices.", website: "https://www.beachfleischman.com", source: "claude_code" },
  { slug: "heinfeld-meech-tucson", name: "Heinfeld, Meech & Co.", contact: "Team", title: "CPA", email: null, city: "tucson", cityLabel: "Tucson", province: "Arizona", country: "United States", services: ["tax-advisory", "fpa-consulting", "controller-services"], industries: ["healthcare", "professional-services", "real-estate", "construction"], description: "Heinfeld, Meech & Co. is a Tucson CPA firm providing audit, tax, and business advisory services to public and private organizations throughout Arizona since 1986.", website: "https://www.heinfeldmeech.com", source: "claude_code" },
  { slug: "keegan-linscott-tucson", name: "Keegan Linscott & Associates", contact: "Team", title: "CPA", email: null, city: "tucson", cityLabel: "Tucson", province: "Arizona", country: "United States", services: ["tax-advisory", "bookkeeping", "controller-services"], industries: ["professional-services", "healthcare", "retail", "real-estate"], description: "Keegan Linscott & Associates is a Tucson CPA firm providing tax planning, audit, bookkeeping, and accounting services to businesses and individuals across Southern Arizona.", website: "https://keeganlinscott.com", source: "claude_code" },
  { slug: "rcm-llp-tucson", name: "RCM LLP (Regier Carr & Monroe)", contact: "Team", title: "CPA", email: null, city: "tucson", cityLabel: "Tucson", province: "Arizona", country: "United States", services: ["tax-advisory", "fpa-consulting", "bookkeeping"], industries: ["construction", "professional-services", "real-estate", "healthcare"], description: "RCM LLP has over 70 years of experience providing accounting, business consulting, and tax services in Arizona, Kansas, and Oklahoma.", website: "https://www.rcmllp.com", source: "claude_code" },
  { slug: "hinton-burdick-tucson", name: "Hinton Burdick", contact: "Team", title: "CPA", email: null, city: "tucson", cityLabel: "Tucson", province: "Arizona", country: "United States", services: ["tax-advisory", "fpa-consulting", "controller-services"], industries: ["healthcare", "professional-services", "construction", "manufacturing"], description: "Hinton Burdick is a CPA firm serving Tucson and the Southwest with audit, tax, and consulting services, known for their commitment to community-focused advisory.", website: "https://www.hintonburdick.com", source: "claude_code" },

  // ── Extra firms to reach 100 ──────────────────────────────────────
  { slug: "focuscfo-louisville", name: "FocusCFO - Louisville", contact: "Team", title: "", email: null, city: "louisville", cityLabel: "Louisville", province: "Kentucky", country: "United States", services: ["fractional-cfo", "fpa-consulting", "controller-services"], industries: ["manufacturing", "professional-services", "healthcare", "technology"], description: "FocusCFO provides experienced fractional CFOs in Louisville who work collaboratively to develop customized financial plans with onsite, remote, or hybrid options.", website: "https://www.focuscfo.com", source: "claude_code" },
  { slug: "world-tax-cpa-lv", name: "World Tax & Accounting - Las Vegas", contact: "Team", title: "CPA", email: null, city: "las-vegas", cityLabel: "Las Vegas", province: "Nevada", country: "United States", services: ["fractional-cfo", "tax-advisory", "bookkeeping"], industries: ["hospitality", "professional-services", "retail", "real-estate"], description: "World Tax and Accounting provides fractional CFO services, tax preparation, bookkeeping, and expert financial leadership tailored to Las Vegas businesses.", website: "https://worldtaxcpa.com", source: "claude_code" },
  { slug: "now-cfo-cincinnati", name: "NOW CFO - Cincinnati", contact: "Team", title: "", email: null, city: "cincinnati", cityLabel: "Cincinnati", province: "Ohio", country: "United States", services: ["fractional-cfo", "controller-services", "bookkeeping"], industries: ["manufacturing", "technology", "professional-services", "healthcare"], description: "NOW CFO provides expert fractional CFO service in Cincinnati with interim support at the CFO, controller, and staff accountant levels.", website: "https://nowcfo.com", source: "claude_code" },
  { slug: "focuscfo-birmingham", name: "FocusCFO - Birmingham", contact: "Team", title: "", email: null, city: "birmingham", cityLabel: "Birmingham", province: "Alabama", country: "United States", services: ["fractional-cfo", "fpa-consulting", "controller-services"], industries: ["healthcare", "manufacturing", "construction", "professional-services"], description: "FocusCFO provides fractional CFO services in the Birmingham metro area, matching businesses with experienced financial leaders for strategic guidance.", website: "https://www.focuscfo.com", source: "claude_code" },
];

// ── Main ──────────────────────────────────────────────────────────────
async function main() {
  console.log(`\nPreparing to insert ${newFirms.length} firms...\n`);

  // 1. Fetch existing firms for duplicate check
  const { data: existing, error: fetchErr } = await supabase
    .from('firms')
    .select('slug, name, website');

  if (fetchErr) {
    console.error('Failed to fetch existing firms:', fetchErr.message);
    process.exit(1);
  }

  const existingNames = new Set(existing.map((f) => f.name.toLowerCase()));
  const existingWebsites = new Set(
    existing.filter((f) => f.website).map((f) => f.website.replace(/\/+$/, '').toLowerCase())
  );
  const existingSlugs = new Set(existing.map((f) => f.slug));

  // 2. Filter out duplicates
  const toInsert = [];
  const skipped = [];

  for (const firm of newFirms) {
    const normName = firm.name.toLowerCase();
    const normWeb = firm.website ? firm.website.replace(/\/+$/, '').toLowerCase() : '';

    if (existingSlugs.has(firm.slug)) {
      skipped.push({ name: firm.name, reason: 'duplicate slug' });
    } else if (existingNames.has(normName)) {
      skipped.push({ name: firm.name, reason: 'duplicate name' });
    } else if (normWeb && existingWebsites.has(normWeb)) {
      skipped.push({ name: firm.name, reason: 'duplicate website' });
    } else {
      toInsert.push({
        slug: firm.slug,
        name: firm.name,
        contact: firm.contact || null,
        title: firm.title || null,
        email: firm.email || null,
        city: firm.city,
        city_label: firm.cityLabel,
        province: firm.province,
        country: firm.country,
        services: firm.services || [],
        industries: firm.industries || [],
        description: firm.description || null,
        website: firm.website || null,
        plan: 'free',
        priority_score: 0,
        status: 'active',
        submitted_by: 'admin',
        source: firm.source || 'claude_code',
      });

      // Track so subsequent entries in this batch also check
      existingSlugs.add(firm.slug);
      existingNames.add(normName);
      if (normWeb) existingWebsites.add(normWeb);
    }
  }

  if (skipped.length) {
    console.log(`Skipped ${skipped.length} duplicates:`);
    skipped.forEach((s) => console.log(`  ✗ ${s.name} — ${s.reason}`));
    console.log('');
  }

  if (!toInsert.length) {
    console.log('No new firms to insert.');
    return;
  }

  // 3. Insert in batches of 50
  const BATCH = 50;
  let inserted = 0;

  for (let i = 0; i < toInsert.length; i += BATCH) {
    const batch = toInsert.slice(i, i + BATCH);
    const { error } = await supabase.from('firms').insert(batch);
    if (error) {
      console.error(`✗ Batch ${Math.floor(i / BATCH) + 1} failed:`, error.message);
    } else {
      inserted += batch.length;
      console.log(`✓ Inserted batch ${Math.floor(i / BATCH) + 1}: ${batch.length} firms`);
    }
  }

  console.log(`\n✓ Total inserted: ${inserted} firms`);

  // 4. Stats
  console.log('\n── Stats ──────────────────────────────────────────');
  const { count: total } = await supabase
    .from('firms')
    .select('*', { count: 'exact', head: true });
  console.log(`Total firms: ${total}`);

  const { data: allFirms } = await supabase
    .from('firms')
    .select('city, city_label, country, email');

  // Count by country
  const byCountry = {};
  allFirms.forEach((f) => {
    byCountry[f.country] = (byCountry[f.country] || 0) + 1;
  });
  console.log('\nBy country:');
  Object.entries(byCountry)
    .sort((a, b) => b[1] - a[1])
    .forEach(([c, n]) => console.log(`  ${c}: ${n}`));

  // Top 30 cities
  const byCity = {};
  allFirms.forEach((f) => {
    const key = f.city_label || f.city;
    byCity[key] = (byCity[key] || 0) + 1;
  });
  console.log('\nTop 30 cities:');
  Object.entries(byCity)
    .sort((a, b) => b[1] - a[1])
    .slice(0, 30)
    .forEach(([c, n], i) => console.log(`  ${i + 1}. ${c}: ${n}`));

  // Emails
  const withEmail = allFirms.filter((f) => f.email).length;
  console.log(`\nFirms with email: ${withEmail} / ${allFirms.length}`);
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
